default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: portal-solar-dev-test_development


test:
  <<: *default
  database: portal-solar-dev-test_test
 

production:
  <<: *default
  database: portal-solar-dev-test_production
  username: portalsolar
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>